# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-30 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
